# -*- coding: utf-8 -*-
"""da41 short hand if else statment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QdE5R5wPzM3fLG_4BA8wo6lvKNcwbNt0
"""

# short hand if else statment

"""
A shorthand if-else statement, also known as a ternary operator, is a concise way to express a conditional statement in programming. It provides a compact syntax for evaluating a condition and returning one of two values based on whether the condition is true or false."""

num=-5
result="positive" if num>0 else "negative"
print(result)

#check if a number is ven or odd
num=10
result="Even" if num%2 ==0 else "odd"
print(result)

#Determine the maximum of two numbers
a,b=15,20
maximum=a if a> b else b
print(maximum)

#check  if the string is empty
string=""
message="not empty" if string else "Empty"
print(message)

#convert a boolean to "yes" or  "No"
is_true=True
response="Yes" if is_true else "No"
print(response)

#check if the a numer is within s specific range
num =25
result="In range" if 10 <= num <= 30 else "out or range"
print(result)

#check if the list is empty
my_list=[1,2,3]
status="Not empty" if my_list else "Empty"
print(status)

#check if the year is leep year or not
year = 2024
leap_year="Leap year" if year %4 ==0 and (year% 100!=0) else "Not a leap year"
print(leap_year)

#Determin the sigh of the number
num=-8
sign="Positve " if num > 0 else "Zero" if num ==0 else "Negative"
print(sign)

#check if the list contain specific element or not
my_list=[1,2,3,4,5]
element=3
contains_element="Element found" if element in my_list else "Element is not found"
print(contains_element)

#display a diffrent message for the even and odd
num =7
message =" this is the even number " if num % 2 ==0 else " This is no the even number"
print(message)

#check if the number is perfect squar are not
num=9
is_perfect_square ="perfect square" if num**0.5 ==int(num**0.5) else "Not  aperfect square"
print(is_perfect_square)

x, y = 3, -2
quadrant = 1 if x > 0 and y > 0 else 2 if x < 0 and y > 0 else 3 if x < 0 and y < 0 else 4 if x > 0 and y < 0 else "Origin"
print(quadrant)

#determine the type of a traingle based on side length
a,b,c=3,4,5
traingle_type="Eaualateral" if a==b==c else "Isosceles" if a==b or a==c  else "Scalene"
traingle_type

