# -*- coding: utf-8 -*-
"""Day16 match Statement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qH61-HX6zubog6qonv-nF2wWtzgymC-x
"""

from typing import Match
def example_1(value: int) ->str:
  match value:
    case 1:
      return "one"
    case 2:
      return "Two"
    case _:
      return "other"
print(example_1(2))

def example_2(data: list) -> str:
  match data:
    case [1,2,3]:
       return "Pattern matched"
    case _:
      return "Pattern not matched"
print(example_2([1,2,3,4,5]))

print(example_2([1, 2, 3]))  # Output: Pattern matched

# Example 3: Matching types
def example_3(value: Match[int | str]) -> str:
    match value:
        case str:
            return "Integer"
        case str:
            return "String"

print(example_3(42))      # Output: Integer
print(example_3("hello"))

def example_4(value: int) -> str:
  match value:
    case x if x>0:
      return "Positive"
    case x if x<0:
      return "Negative"
    case 0:
      return "Zero"
print(example_4(3))
print(example_4(-5))
print(example_4(0))

def example_5(data: tuple) ->str:
  match data:
    case(0,0):
      return "Origin"
    case (x,0):
      return f"On x_axis at {x}"
    case (0,y):
      return f"On y_axis at {y}"
    case(x,y):
      return f" At coordinates ({x},{y})"
print(example_5((0,0)))
print(example_5((2,0)))
print(example_5((0,3)))
print(example_5((4,5)))
print(example_5((4,2)))

