# -*- coding: utf-8 -*-
"""Day1-Intro to Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cm272XTM0MaAwnrzj7e7EIpWiV2LIrCZ

What is Programming

Programming is a way for us to tell computers what to do. Computer is a very dumb machine and it only does what we tell it to do. Hence we learn programming and tell computers to do what we are very slow at - computation. If I ask you to calculate 5+6, you will immediately say 11. How about 23453453 X 56456?

You will start searching for a calculator or jump to a new tab to calculate the same. This 100 days of code series will help you learn python from starting to the end. We will start from 0 and by the time we end this course, I promise you will be a Job ready Python developer!

What is Python?

1. Python is a dynamically typed, general purpose programming language that supports an object-oriented programming approach as well as a functional programming approach.
2. Python is an interpreted and a high-level programming language.
3. It was created by Guido Van Rossum in 1989.

Features of Python

1. Python is used in Data Visualization to create plots and graphical representations.
2. Python helps in Data Analytics to analyze and understand raw data for insights and trends.
3. It is used in AI and Machine Learning to simulate human behavior and to learn from past data without hard coding.
4. It is used to create web applications.
5. It can be used to handle databases.
6. It is used in business and accounting to perform complex mathematical operations along with quantitative and qualitative analysis.

Why Google Colab?

Google Colab, short for Colaboratory, is a free, cloud-based platform provided by Google that allows you to write and execute Python code in a collaborative environment. Here are some of the key features of Google Colab:

Free Access to GPU and TPU:

Colab provides free access to Graphics Processing Units (GPUs) and Tensor Processing Units (TPUs), allowing users to accelerate their machine learning computations. This is particularly useful for training deep learning models.
Cloud-based Execution:

Since Colab is cloud-based, you can access your notebooks and run code from any device with an internet connection. This eliminates the need for powerful local hardware.
Integration with Google Drive:

Colab is integrated with Google Drive, making it easy to save and share your work. Colab notebooks are stored in Google Drive, and you can share them just like you would with Google Docs or Sheets.
Pre-installed Libraries:

Colab comes with many pre-installed libraries for data analysis, machine learning, and deep learning, such as NumPy, pandas, TensorFlow, and PyTorch. This saves users from having to install these libraries manually.
Collaborative Editing:

Multiple users can collaborate on the same Colab notebook in real-time. Each collaborator is assigned a different color, and changes made by one user are visible to others instantly.
Code Snippet Sharing:

Colab allows users to share their code snippets easily. You can generate a shareable link to a Colab notebook, making it straightforward to distribute code for collaboration or demonstration purposes.
Interactive Visualizations:

Colab supports the display of interactive visualizations using libraries like Matplotlib, Plotly, and others. This is beneficial for data exploration and analysis.
Markdown Support:

Colab supports Markdown cells, enabling users to create formatted text, headers, lists, and embed images in their notebooks to provide documentation and explanations alongside the code.
Version History:

Colab automatically saves version history, allowing users to revert to previous versions of their notebooks. This is useful for tracking changes and recovering from mistakes.
Access to Google Cloud Services:

Colab allows access to Google Cloud services, enabling users to leverage cloud resources and services for tasks such as data storage and processing.
Integration with GitHub:

Colab notebooks can be easily shared on GitHub, and you can open notebooks directly from GitHub or save them to GitHub.
Overall, Google Colab is a powerful tool for various tasks in data science, machine learning, and collaborative coding, especially when resources like GPUs and TPUs are needed.
"""







