# -*- coding: utf-8 -*-
"""day15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H1drdBIM1s46JSRJQ8Um6LDqK34s3UtM
"""

import datetime

def greet():
    current_time = datetime.datetime.now().time()

    # Define time ranges for greetings
    morning_start = datetime.time(6, 0, 0)
    morning_end = datetime.time(12, 0, 0)
    evening_start = datetime.time(18, 0, 0)
    evening_end = datetime.time(23, 59, 59)

    # Check the current time and greet accordingly
    if morning_start <= current_time <= morning_end:
        print("Good morning!")
    elif evening_start <= current_time <= evening_end:
        print("Good evening!")
    else:
        print("Hello!")

# Call the greet function
greet()

