# -*- coding: utf-8 -*-
"""Day18 while loops in python .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WH_Oio7010VmihMatQc98uJ39C99jUBd
"""

i=int(input("Enter the number:"))
print(i)
while(i<=30):
  i=int(input("Enter the number:"))
  print(i)
print("done with the loop")

count=5
while (count>5):
  print(count)
  count=count-1
else:
  print("I am iside else")

#Nested Loops to print multiplication Table:
for i in range(1,11):
  j =1
  while j<=10:
    print(i*j,end="\t")
    j+=1
  print()

for i in range(1, 11):
    j = 1
    while j <= 10:
        print(i * j, end="\t")
        j += 1
    print()

# Calsulate FActorial using for and while lops:
num=5
factorial=1
for i in range(1,num+1):
  factorial*=i
print(f"The factorail of {num } is {factorial}")

# sum of NUmbers up to a limit with while Loops inside For Loop :
limit=5
sim_numers=0
for i in range(limit):
  j=0
  while j<=i:
    sum_numbers+=j
    j+=1
print("sum of numbers:",sum_numbers)

for i in range(1,6):
  j=1
  while j<=i:
    print("*",end="")
    j+=i
  print()

count=0
while count<5:
  print(count)
  count +=1

a,b=0,1
while a<20:
  print(a, end=" ")
  a,b=b,a+b

#factorail Calculation
n=int(input("Enter a number:"))
factorial =1
while n>1:
  factorial*=n
  n-=1
print("Factoral:",factorial)

# password =" "
# while password!="secret":
#   password=input("Enter the password:")
#   print("Access granted!")

sum_numbers=0
while sum_numbers<10:
  print("Current Sum:",sum_numbers: )
  sum_numbers+=sum
print("sum reached 10 or more.")

