# -*- coding: utf-8 -*-
"""Day13 String methods.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e56OYyZTG4uKVaG7UmPqpyyHbP_RSLIj

Python provides a set of built - in method  the we can use to alter and modify the string
"""

# Uppper():
str1="Afgedfsdfgh"
print(str1.upper())
print(str1)

"""Lower():
The lower method converts a string to  lower case.
"""

str1="Venkatesh J Mariayappanaver"
print(str1.lower())

"""strip():

the strip method removers any whithe sopace before and after the string
"""

str2=" Silver Spoon "
print(str2.strip())

"""rstrip():

the strip() remove any trailing  characters, Example
"""

str3="Hello, !!!"
print(str3.rstrip("!"))

"""replace():
 The replace method replaces all occurencess of a string with another string. Example:

"""

str2="Silver Spoon"
print(str2.replace("Sp","M"))

str2="Silver spoon"
print(str2.replace("Silver", " gold"))

"""Split():
 the split method splis the given string at the specified string at the specified instace and returns the separated string as list iterms.
"""

str2="Silver Spoon"
print(str2.split(" "))

"""Cappitaliz():

"""

# The Capitalize turns only the forst character of the string to uppercase
#  and the rest other character of the string are turened to  lowercase. the st
#  the string has no effect of the first character is alredy
#  uppercaselll

str1 = "hello"
capStr1 = str1.capitalize()
print(capStr1)
str2 = "hello WorlD"
capStr2 = str2.capitalize()
print(capStr2)

"""Cetner():
The center() metheod aligns the string to the center as per the parameters give n by the user
"""

str1="Welcome to the consle!!!"
print(str1.center(50))

"""Welcome to the console!!!"""

# We can also provide chanracter, It will fill the rest of the fill chanracter pr
# provided by the user

str1="Welcome to the console!!!"
print(str1.center(50,"."))

"""count():
The count() method returns the number  of times the given  value has occurred within the given string.
"""

str2 ="venkatesh jayappa Mariyappanaver"
countstr=str2.count("a")
print(countstr)

"""endwith():

We can even also check for  a value in between the string by providing start and end  index positions.
"""

str1 = "Welcome to the Console !!!"
print(str1.endswith("to",4,10))

"""Find():

the find() method searches for the first occurrences of the given value and returns the iundex where it is present where it it present , If given value is absent from the string then return-1
"""

str1="Hi's name is Dan. he is an honest man."
print(str1.find("is"))

"""As we can see, this method is somewhat similar to the index() method. The major diffrences being that index() raises an exception if value is absent where find() does not.

index():

The index() method search for the occurence  of the  given value and returns the index where it is present. If given  value is absent from the string thean raise an exception
"""

# EXample:
str1=" Hi 's name is Dan is an honest man."
print(str1.index("Dan"))

"""As we can seem  this method is somewhat similar to the find() method. The major diffrence being that index() raises an exception if value is absent whereas find()d does not.

isalnum():  the isalnum() returns True only if the entair string only consists of A-Z, a-z , 0-9 If any other characters  or punctuuation are present m that it returns False
"""

str1="WElcomeToConsole"
print(str1.isalnum())

"""isalpha():
The isalnum() method return True only if the entire string only consistes of A-Z ,a-z If any other Characters or punctiations or numers(0-9) are present, then it returns False.
"""

str1="Welcome"
print(str1.isalpha())

"""islower():
the islower(): method returns True if all the chanracters in thestring are lower case, else it  returns False.
"""

str1="hello World"
print(str1.islower())

"""isprintable():
The isprintable() method returns True if all True if all not, then return False.
"""

str1="We wish you a Merry Caristmas"
print(str1.isprintable())

"""isspace():
The isspace() method returns  True only  if the string cotains white spaces,else retruns False
"""

str1="      "
print(str1.isspace())
str2="        "
print(str2.isspace())

"""istitle():

The istitle() returns True only if the first letter of each world of the string is capitalized, else it retuns False.
"""

str2="To kill a Mocking bird"
print(str2.istitle())

"""isupper():
the isupper() method returns True if all the characters in the string are ipper case, else case, else it returns False.
"""

str1="WORLD HEALTH oRGANIZATION"
print(str1.isupper())

"""startwith():
 The endswith() method check if the string starts with a given value. If yes than return True,else return False.
"""

str1 = "Python is a Interpreted Language"
print(str1.startswith("Python"))

"""swapcase():"""

#the swapcase() method changes the character casing of the string Upper case are  converted to lower case and lower case to upper case.

str1 ="Python is a Interprited Languages"
print(str1.swapcase())

"""title():

 The title() method capitalizes each letter of the world within the string.
"""

str1=" He's name is Dan. Dan is an honest  man."
print(str1.title())

