# -*- coding: utf-8 -*-
"""Day25 operations on tuple.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ihmqpvBBnHVPtq7bm_zJj2iJuqDH1RTu
"""

# creating  a tuple:
my_tuple=(1,2,3,4,5)
print(my_tuple)

# accessing  element:
print(my_tuple[0])

#slicing
subset=my_tuple[1:4]
print(subset)

# concatination:
new_tuple=my_tuple+(4,5,6)
print(new_tuple)

# Repetition:
repeted_tuple=my_tuple*2
print(repeted_tuple)

# Length:
length=len(my_tuple)
print(length)

#Membership Test:
print("a" in my_tuple)

# count:
count_a = my_tuple.count("a")
print(count_a)

# index:
index_2=my_tuple.index(2)
print(index_2)

min_val=min((3,1,4,1,5,9,2))
max_val=max((3,1,4,1,5,9,2))
print(max_val,min_val)

# copnversion to tuple:
list_to_tuple=tuple([1,2,3,4])
print(list_to_tuple)

# interating throught the tuple:
tuple1=(1,2,3,"venki","raju","ravi")
for  i in tuple1:
  print(i)

# Tuple Unpaking:
a,b,c=my_tuple[:3]
print(a,b,c)

# checking for equality:
tuple1=(1,2,3)
tuple2=(1,2,3)
print(tuple1==tuple2)

# sorting:
sorted_tuple=tuple(sorted((3,3,4,5,6,7,4556,2)))
print(sorted_tuple)

# finding the sum:
sum_tuple=sum((1,2,3,4,5))
print(sum_tuple)

# Getting the Minimum and Maximum Element:
min_element=min((1,2,3,4,5))
max_element=min((1,2,3,4))
print(min_element,max_element)

# checking for Emptiness:
empty_tuple=()
if not empty_tuple:
  print("Tuple is empty")

#  Using any and all:
bool_tuple=(True,False,True)
any_result=any(bool_tuple)
all_result=all(bool_tuple)
print(any_result,all_result)

tuple_to_list = list(my_tuple)
tuple_to_set = set(my_tuple)
print(tuple_to_list, tuple_to_set)

