# -*- coding: utf-8 -*-
"""Day3-Modules and pip in Python!.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13WsMCcxd7yB0I5QSV76Z-6pkXz-L2CB1

Modules and pip in Python!

Module is like a code library which can be used to borrow code written by somebody else in our python program. There are two types of modules in python:

1. Built in Modules - These modules are ready to import and use and ships with the python interpreter. there is no need to install such modules explicitly.
2. External Modules - These modules are imported from a third party file or can be installed using a package manager like pip or conda. Since this code is written by someone else, we can install different versions of a same module with time.

The Pip command

It can be used as a package manager pip to install a python module. Lets install a module called pandas using the following command

To approch modules we use the pip commad
"""

# pip install pandas

"""Using a module in Python (Usage)"""

# import pandas as pd
# pd.read_csv("word file")
# print(df)