# -*- coding: utf-8 -*-
"""day35 for loop in python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10_pI1y5Xm5LAi58scUfaG5prcxCw0xpC

Python -else in Loop


 as you have lerned before, the else clause is used along with the if statement.


Python allows the else keybord to be used with the for loops to. the else block appers the body of the lop The statments in the else block wioll be executed exits the loop only after iterations are completed The program exits the loop only after the else block executed.

Syntax
for counter in sequence:
  # statment inside for loop block
else:
   # Statements inside else block
"""

for x in range(5):
  print("iterations no {} for Loop".format(x+1))
else:
  print("else block in loop ")
print("OUt of loop")

i = 0
while i<7:
  print(i)
  i = i + 1
  # if i == 4:
  #   break

else:
  print("Sorry no i")

for x in range(5):
    print ("iteration no {} in for loop".format(x+1))
else:
    print ("else block in loop")
print ("Out of loop")

# print numbers form 1 to 5
for i in range(1,6):
  print(i)

# Calculate the sum of numbers for 1 to 5
sum_result=0
for i in range(1,6):
  sum_result +=i
print("Sum:",sum_result)

# print even numbers forn 2 to 20
for i in range(2,11,2):
  print(i)

# find the product opf numbers 1 to 5 :
product_result=1
for i in range(1,6):
  product_result *=i
print("prooduct:", product_result)

# print th square of numbers from 1 to 4
for i in range(1,5):
  print(i**2)

# print the reverse of a string:
my_string ="hello"
reverse_string = ""
for char in reversed(my_string):
  reverse_string +=char
print(reverse_string)

# count the numbers of vowels in a string
my_string="python programing"
vowel_count = 0
for char in my_string:
  if char.lower() in "aeiou":
    vowel_count  +=1
print("Vowel count:",vowel_count)

# print the factorail of a  number (e.g, factorail)
n=5
factorial_result =1
for i in range(1,n+1):
  factorial_result *=i
print(f"{n} factorial:",factorial_result)

# factorail of number using the for loop
def fact(n):
  if (n==0 or n==1):
    return 1
  else:
    return (n * fact(n-1))
fact(5)

# check if a number is prime
num = 7
is_prime = True
for i in range(2, int(num**0.5) + 1):
    if num % i == 0:
        is_prime = False
        break
print(f"{num} is prime:", is_prime)

# print a pattern
for i in range(1,6):
  print("*"*i)

# clalculater the  average  of a list numbers
numbers = [10, 20, 30, 40, 50]
average = sum(numbers) / len(numbers)
print("Average:", average)

# Find the maximum element in a list
numbers =[5,8,3,12,7]
max_num =numbers[0]
for num in numbers:
  if num > max_num:
    max_num=num
print("Maximum:",max_num)

# Calculate the power of a number
base= 2
exponent = 3
result = 1
for _ in range(exponent):
  result *=base
print(f"{base} raised to the power of {exponent}:", result)

my_string = "level"
is_palindrome = True
for i in range(len(my_string) // 2):
    if my_string[i] != my_string[-i - 1]:
        is_palindrome = False
        break
print("Is palindrome:", is_palindrome)

# print Fibonacci sequence
fibonacci_sequence =[0,1]
for i in range(2,n):
  fibonacci_sequence.append(fibonacci_sequence[-1] + fibonacci_sequence[-2])
print(fibonacci_sequence)

celsius_temps = [0, 10, 20, 30, 40]
for celsius in celsius_temps:
    fahrenheit = (celsius * 9/5) + 32
    print(f"{celsius} Celsius is {fahrenheit:.2f} Fahrenheit")

