# -*- coding: utf-8 -*-
"""day42 enumerate funcion in python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xFVkJKrclUngy0qQ2dNXO52dsgWfXPes
"""

#Example1  Basic usage
fruits =["apple", "banana","cherry"]
for index,fruit in enumerate(fruits):
  print(index,fruit)

# example3 Enumerating a stirng
word='python'
for index,letter in enumerate(word):
  print(index,letter)

#Example 4: Enumerating a list of tuple
pairs=[(1,"one"),(2,"two"),(3,"three")]
for index, pair in enumerate(pairs):
  print(index,pair)

# Example 5 unpaking the tuple element
for index,(numer,word) in enumerate(pairs):
  print(index,numer,word)

#EXample enumarate with the dict
colors={"rd":1,"green":2,"blue":3}
for index,(color,value) in enumerate(colors.items()):
  print(index,color,value)

#Example 7 enumerating lines in a file
with open('example.txt', 'r') as file:
    for line_num, line in enumerate(file, start=1):
        print(line_num, line.strip())

# EXample 8 : Enumerate with a custom starting index
for index,element in enumerate(["a","b","c"],start=10):
  print(index,element)

#Example 9 Enumerate with a sustom starting index
for index,element in enumerate(["a","b","c"],start=10):
  print(index,element)

#example9using the enumerate with the set
my_set={"apple","range","banana"}
for index,item in enumerate(my_set):
  print(index,item)

#Example 10 Enumerating backwards
for index,item in enumerate(reversed(fruits)):
  print(index,item)

#Example 11: Enumerating with a step
for index,item in enumerate(fruits[::]):
  print(index,item)

#Example 13: Using enumerate in  list comprehension
indexed_fruits=[(index,fruit) for index, fruit in enumerate(fruit)]
print(indexed_fruits)

for index in range(len(fruits)):
  print(index,fruits[index])

#Example15 Enumeration with mupltiple lists
colors=["red",'green',"blue"]
for index,(fruit,color) in enumerate(zip(fruits,colors)):
  print(index,fruit,color)

#Example 16 Enumerating with multiple lists
colors=["red","green",'blue']
for index,(furit,color) in enumerate(zip(fruits,colors)):
  print(index,fruit,color)

#example 16: enumerating with unpaking and starting index
for i, (a,b,c) in enumerate([(1,2,3),(4,5,6)],start=100):
  print(index,fruit,color)

#example 17 Enuemrate with a custom class
class MyClass:
    def __init__(self, value):
        self.value = value

objects = [MyClass('one'), MyClass('two'), MyClass('three')]
for index, obj in enumerate(objects):
    print(index, obj.value)

#Example 18 using enuemrate with a generator expression
gen =(x for x in range(5))
for index,value in enumerate(gen):
  print(index,value)

#Example 18: using enumerate with a generator expression
for index, item in enumerate(reversed(range(0,10,2))):
  print(index,item)

# Example20 Enuemrating with a step in a reversed sequence
for index, char in enumerate("Python",step=2):

    print(index, char)

