# -*- coding: utf-8 -*-
"""day45if_name_==_main__ .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OBYup00r6dBR2jIYf1U58eBNOD9JWELR

if __name__ == "__main__": construct in Python. This code block is commonly used to check whether the Python script is being run as the main program or if it is being imported as a module into another script. This allows you to have code that is executed only when the script is run directly, not when it is imported.
"""

# 'Example 1 simple script
def greet(name):
  print(f"hello,{name}!")
if __name__=="__main__":
  user_name=input("Enter Your name:")
  greet(user_name)

import example_script

# Example 3: Calculation script

def add_numbers(a, b):
    return a + b

def subtract_numbers(a, b):
    return a - b

if __name__ == "__main__":
    # This block will be executed only if the script is run directly
    num1 = int(input("Enter the first number: "))
    num2 = int(input("Enter the second number: "))

    result_sum = add_numbers(num1, num2)
    result_diff = subtract_numbers(num1, num2)

    print(f"Sum: {result_sum}")
    print(f"Difference: {result_diff}")

re