# -*- coding: utf-8 -*-
"""day40 secret code language.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MjDSkOrrnZkfZs8hODxklx-G5orltiF
"""

import random

def encode(word):
    if len(word) >= 3:
        first_letter = word[0]
        word = word[1:] + first_letter
        secret_code = random.choices('abcdefghijklmnopqrstuvwxyz', k=3) + list(word) + random.choices('abcdefghijklmnopqrstuvwxyz', k=3)
        return ''.join(secret_code)
    else:
        return word[::-1]

def decode(word):
    if len(word) < 3:
        return word[::-1]
    else:
        random_chars = word[:3] + word[-3:]
        decoded_word = word[3:-1] + word[0]
        return decoded_word

def main():
    choice = input("Do you want to code or decode? Enter 'code' or 'decode': ").lower()

    if choice == 'code':
        message = input("Enter the message to encode: ")
        coded_message = ' '.join(encode(word) for word in message.split())
        print("Encoded Message:", coded_message)
    elif choice == 'decode':
        message = input("Enter the message to decode: ")
        decoded_message = ' '.join(decode(word) for word in message.split())
        print("Decoded Message:", decoded_message)
    else:
        print("Invalid choice. Please enter 'code' or 'decode'.")

if __name__ == "__main__":
    main()

