# -*- coding: utf-8 -*-
"""Day4-Our first Python  Progam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SIymuIEoeXNTxjJWj8gHjMtF76xMwFTD
"""

print("Hlle World")
print('Our first python program')
print("this viwer is  good by/girl")
print("This is the 100 days of machine learing class",100,"and this is conduclted by the venkatesh jayappa mariyappnaver")

print(13*32)

print(23+23)

