# -*- coding: utf-8 -*-
"""day49 Io in python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KqoyxHVxWlUKR3AZ-AKZfRaGTq3crcfX

r Mode:
# open the file for reading

1. 'r' - Read Mode:
Opens the file for reading.

2. 'w' - Write Mode:
Opens the file for writing.
If the file doesn't exist, it creates a new file.
If the file already exists, it truncates the file to zero length.

3. 'a' - Append Mode:
Opens the file for writing, but appends new content to the end of the file.
If the file doesn't exist, it creates a new file.


4. 'b' - Binary Mode:
Reads or writes the file in binary mode.

Example (Reading binary data):


5. 'x' - Exclusive Creation:
Creates a new file but raises an error if the file already exists.

6. '+' - Read and Write Mode:
Opens the file for both reading and writing.
"""

try:
    # Open the file
    with open("my_file.txt", "r") as f:
        print(f)  # Print file object information

        # Read the content of the file
        text = f.read()
        print("File Content:")
        print(text)
except FileNotFoundError:
    print("Error: File not found.")
except PermissionError:
    print("Error: Permission denied to read the file.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
# reading the file
g=open("my_file2.txt","r")
text=g.read()
print(text)
# writing to the file
new=open("my_writingfile.txt","a")
f.write("Hello,  this is the python world this  world is  butiful world")
text=new.read()
print(text)
new.close()
f=open("my_file.txt","a")
f.write("hello, world!")
with  open("my_file.txt","a")as f:
    f.write("Hey I am insdie with")
# opening the file with the read mode
with open("example.txt","w") as file:
    content=file.read()
    print(content)

# "w" Write Mode:
# open the file for writing
# if the file does't exist it create a new file
# if the file already exists , it truncates the file to zero lenght
with open("new_file.txt","w")as file:
    file.write("Hello, this is new file!")

with open("binary_file.bin", "rb") as file:
    binary_data = file.read()
    print(binary_data)

with open("new_binary_file.bin", "wb") as file:
    file.write(b'\x48\x65\x6C\x6C\x6F')  # Writing binary data (e.g., ASCII values for "Hello")

try:
    with open("exclusive_file.txt", "x") as file:
        file.write("This is an exclusive file.")
except FileExistsError:
    print("File already exists.")

with open("read_write_file.txt", "r+") as file:
    content = file.read()
    print("Read Content:", content)

    file.write("\nAppending new content.")

