# -*- coding: utf-8 -*-
"""Day5-Comments-Escape-Print statment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yaQQ_jU8ElO9A-d6PqzupZTbZ6srO1Kf

Comments

In Python, comments are used to add explanatory notes or remarks within the code. Comments are ignored by the Python interpreter and serve the purpose of making the code more readable and understandable. There are two types of comments in Python:

Single-Line Comments:

Single-line comments begin with the # symbol. Everything on the line following the # is considered a comment.
"""

# This is the single line comment
# this is the first program
print("hello world ")

"""Although Python doesn't have a specific syntax for multi-line comments, you can use triple quotes (''' or ''') to create multi-line strings, and these are often used as a workaround for multi-line comments."""

# Multi line Comments
"""this is the multi line comments this prorgamming language is not a compailed language"""

''' this is the multi-line
comments spanning the multiple lines'''
print("this is the multiple ,ine comments")

"""another way to do the multiline comments is starting the line with the # symbol

"""

# this is the multi line comments or the programming the
# it help the programer to understand the program clearly

"""While single-line comments are more common, the choice between single-line and multi-line comments depends on the context and personal or team preferences.

It's good practice to include comments in your code to explain complex sections, provide context, or make notes about the code's purpose. However, it's also important to write code that is self-explanatory whenever possible, as overuse of comments may indicate code that could be made more readable through better naming and structure.

Escape characters in Python are special characters that are used to represent non-printable or special characters within strings. They are preceded by a backslash \. Here are some commonly used escape characters in Python
"""

#Insert the newline character
print("Hello\n world ")

# Insert the tab
print("Hello\t world")

# Allow you to insert the single or doulbe quots within  a string
print('she said , "hello!')

#Insert  a literal backslash
print("this is a backslash:\\ ")

#Move the coursor to the beginning ot the line
print("Hello\rWorld")

#Move the cousor back one space
print("Hello\bWorld")
# Output: HellWorld

#Produces an audible alert (bell) on some systems.
print("This is an alert\a!")
# Output: This is an alert!

#Allows you to include Unicode characters in a string.
print("smilley: \U0001F604")

print("Greek Delta: \u0394")
# Output: Greek Delta: Δ

"""
More on print statment"""

# print(object(s), sep=separator, end=end, file=file, flush=flush)

