# -*- coding: utf-8 -*-
"""Day7 Operators in Python .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wfnTrqmkVkA36dVsbUPbBGMLBOz5yEiW

**Operaters in Python **
"""

# Arithemetics Operaters
# addition
# Substraction
# Multiplication
# Substraction
# Division
# Modulus
# Exponetiation

a=10
b=3
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a//b)
print(a%b)
print(a/b)

"""Comaprison Operators

"""

# 2. comparison  Operators
#  equal to ==
#  Not equal !=
#  Greater than >
#  less than <
#  Greater than or equal to >=
#  Less than or equal to <=

x=5
y=10
print(x==y)
print(x!=y)
print(x<y)
print(x>=y)
print(x<=y)
print(x>y)

"""Logical Operators

"""

# Logical AND
# Logical OR
# Logical NOT

a=True
b=False

print(a and b)
print(a or b )
print(not a )

""" Assignment Operators:"""

# assigh =
# add and assign
# Substract and assign
# Multiply and assign
# Modulus and assign
# Exponentiate ansd assign
# Floor division and assign

x=5
x+=3
print(x)

"""Identity Operators:

"""

# Identity equal 'is '
# Identity not equal  is not

a=[1,2,3,4,5]
b=[1,2,3,4,4,4]
print(a is b )
print(a is not b )
print(a not in b )

"""Membership Operators:

"""

# In 'in'
# Not in "not in "
my_list=[1,2,3,4]
print(3 in my_list)
print(5 not in my_list)

"""simple calculater program in python  using the functrional program"""

def add(x,y):
  return x+y
def subtract(x,y):
  return x-y
def multiplty(x,y):
  return x*y
def divide(x,y):
  if y!=0:
    return x/y
  else:
    return "cannot divide by Zero"
num1=float(input("Enter the first number: "))
num2=float(input("enter the second number: "))
operator= input("Enter the operators(+,-,*,/)")

if operator == '+':
    result = add(num1, num2)
elif operator == '-':
    result = subtract(num1, num2)
elif operator == '*':
    result = multiply(num1, num2)
elif operator == '/':
    result = divide(num1, num2)
else:
    result = "Invalid operator"

print(f"Result: {result}")

import math

# User input
num1 = float(input("Enter the first number: "))
operator = input("Enter the operator (+, -, *, /, sqrt, pow, sin, cos, tan): ")

if operator in ('sqrt', 'sin', 'cos', 'tan'):
    if operator == 'sqrt':
        result = math.sqrt(num1)
    elif operator == 'sin':
        result = math.sin(math.radians(num1))
    elif operator == 'cos':
        result = math.cos(math.radians(num1))
    elif operator == 'tan':
        result = math.tan(math.radians(num1))
else:
    num2 = float(input("Enter the second number: "))

    # Perform calculation based on user input
    if operator == '+':
        result = num1 + num2
    elif operator == '-':
        result = num1 - num2
    elif operator == '*':
        result = num1 * num2
    elif operator == '/':
        if num2 != 0:
            result = num1 / num2
        else:
            result = "Cannot divide by zero"
    elif operator == 'pow':
        result = num1 ** num2
    else:
        result = "Invalid operator"

# Display the result
print(f"Result: {result}")

