# -*- coding: utf-8 -*-
"""day8 simple calculator .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i9D3v3Q8RpeCCZeehs71Ve2AYiI7fdrR
"""

def add(x,y):
  return x+y
def subtract(x,y):
  return x-y
def multiply(x,y):
  return x*y
def divide(x,y):
  if y!=0:
      return  x/y
  else:
    return "Error: division is not possible by zero "
while True:
  print("Select operation: ")
  print("1. Add")
  print("2. subtract")
  print("3. Multoply")
  print("4. Divide")
  print("5. Exit")
  choice=input("Enter the choice(1,2,3,4,5): ")

  if choice in ('1','2','3','4'):
    num1=float(input("Enter the first number "))
    num2 =float(input("Enter the second number"))
    if choice =="1":
      print(num1,"+",num2,"=",add(num1,num2))
    elif choice =="2":
      print(num1,"+",num2,"=",subtract(num1,num2))
    elif choice =="3":
      print(num1,"*",num2,"=",multiply(num1,num2))
    elif choice =="4":
      result=divide(num1,num2)
      print(num1,"/",num2,"=",result)
    else:
      print("Invalid input. Please enter a valid  choice.")
  else:
    print("Invalid input. Please enter a valid choice.")

