# -*- coding: utf-8 -*-
"""Day9-Typecosting in python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_wYTT8X3tI3Ql7YHP6WAxetcbA22tYW
"""

print(type(num_int))

# int (): Convert  a number or a string containg a whole number to the int datatype
num_str="123"
num_int=int(num_str)
print(num_int)

#flaot(): Converts number or a string  cotaing a number to a floating -point number
num_str="1234.34"
num_float=float(num_str)
print(num_float)

print(type(num_float))

#str(): Converts a variale to a string
num= 123
num_str=str(num)
print(num_str)

print(type(num_str))

# bool(): Converts value to a boolean For  example , 'bool(0)' would be False and bool(1) would be the True
num=0
bool_value=bool(num)
print(bool_value)

print(type(bool_value))

# list(),tuple(),set(): Convert other iterable types to a list ,tupel  and set
my_string="hello"
list_version=list(my_string)
print(list_version)

#tuple to list
my_tuple=(1,2,3,4,5)
my_list=list(my_tuple)
print(my_list)

print(type(my_list))
print(type(my_tuple))

my_list=[1,"hello",3.14,True]
my_tuple=tuple(my_list)
print(my_tuple)
print(type(my_tuple))
print(type(my_list))

#set to list
my_set={1,2,3,4,5}
my_tuple=tuple(my_set)

print(type(my_set))
print(type(my_tuple))

# dict to the list as a  keay and the value
my_dict={"a":1, "b":2,"c":3,"d":4}
keys_list=list(my_dict.keys())
print(keys_list)

values_list=list(my_dict.values())
print(values_list)

print("keys list:",keys_list)
print("Values list:", values_list)

pairs_list= list(my_dict.items())
print("Paris list:",pairs_list)

