# -*- coding: utf-8 -*-
"""Day 27koun banega karodpoati.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UVh-_xy2ywuZo-J3hAuKMI61uFTPKakV
"""

import random

def display_question(question, options):
    print(question)
    for i, option in enumerate(options, start=1):
        print(f"{i}. {option}")
    print()

def kbc_game():
    questions = [
        {
            "question": "What is the capital of France?",
            "options": ["Berlin", "Paris", "London", "Rome"],
            "correct_answer": 2,
        },
        {
            "question": "Which programming language is this program written in?",
            "options": ["Java", "Python", "C++", "JavaScript"],
            "correct_answer": 2,
        },
        # Add more questions as needed
    ]

    money_prizes = [0, 1000, 2000, 5000, 10000, 20000, 40000, 80000, 160000, 320000, 640000, 1250000, 2500000, 5000000, 10000000]

    random.shuffle(questions)

    total_prize = 0

    for i, q in enumerate(questions, start=1):
        display_question(q["question"], q["options"])

        answer = int(input("Enter the number corresponding to your answer: "))

        if answer == q["correct_answer"]:
            print("Correct!\n")
            total_prize = money_prizes[i]
        else:
            print(f"Sorry, the correct answer was {q['correct_answer']}. You won {total_prize} rupees.")
            break

    print(f"Congratulations! You won {total_prize} rupees!")

if __name__ == "__main__":
    print("Welcome to Kaun Banega Crorepati!\n")
    kbc_game()

