# -*- coding: utf-8 -*-
"""Day 60 getter and Setter in python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IWZk2ZQcbLoIvX-VNPbwQiDWtXe3xCMt
"""

class Person:
    def __init__(self, name):
        self._name = name

    # Getter method
    def get_name(self):
        return self._name

    # Setter method
    def set_name(self, new_name):
        self._name = new_name

# Usage
person = Person("John")
print(person.get_name())  # Output: John
person.set_name("Doe")
print(person.get_name())

class Circle:
    def __init__(self, radius):
        self._radius = radius

    @property
    def radius(self):
        return self._radius

    @radius.setter
    def radius(self, new_radius):
        if new_radius < 0:
            raise ValueError("Radius cannot be negative")
        self._radius = new_radius

# Usage
circle = Circle(5)
print(circle.radius)  # Output: 5
circle.radius = 7
print(circle.radius)  # Output: 7

class Circle:
    def __init__(self, radius):
        self._radius = radius

    @property
    def radius(self):
        return self._radius

    @radius.setter
    def radius(self, new_radius):
        if new_radius < 0:
            raise ValueError("Radius cannot be negative")
        self._radius = new_radius

# Usage
circle = Circle(5)
print(circle.radius)  # Output: 5
circle.radius = 7
print(circle.radius)  # Output: 7

