# -*- coding: utf-8 -*-
"""varaibles and keywords in python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1brQYM0kubLvZNRcDJgPwWE3C5r2FVIN-
"""

# for data manipulation
# for reusabality
# For Storing result of expression

pi=3.142
r=3
aoc=(3.142*3*3)
print(2*pi*3)
print(pi*r*r)
print(pi*r*r)
print(2*pi*r)
print(aoc)

# How to create varaible in ptyhon ?
# in c int c = 3;
# in ptyhon
age=23
print(type(age))

# Note No need to specifiy the data type of in python becuase of it  of dynamicallly typesd

# How to read the varaible assignment?

salary=6000
# 6000 is assigned to salary
# salary refers to the 6000

# how variable works in the python
# how the how the varaible works in c
# in c the varaible when the varaible is declired  it allocater the memory for the
# different memory allocation for the same value
# when comes to the python it allocates the same memory for the same value varaible

a=100
print(id(a))
b=100
print(id(b))
print("a:",id(a))
print("b:",id(b))

c=a
print("c: ",id(c))
d=200
print("d:",id(d))

# how to assighn the varaible
age=20
print(type(age))
age=age+2
print(age)

# creating the  multiple varaible in on one line
name="shanthanu"
salary=23
name,age,salary="shanthanu",25,3567789
print(name,age,salary)

# How to assign single value to the multiple varaibles
num=23
age=23
value=23
num=age=value=23
print(num,age,value)

# naming convanitons for varaibles creation

# varaible must be start with the alphbet or an underscore(_) (a-z)
# cont use special symbols except underscore(_)
# varaible name should not start with digit
# No white space allowed in varaible varaible names
# varaible in python allowed are case sensitve



# how to delete the varaible in python
a=100
print(a)
del a

#Variable Annotaions
name="shanthanu"
name:str="venki"
print(name)

# How to get all kewiords in python
import keyword
print("Keywords  are :",keyword.kwlist)
# anothe method
# shell
# help
# Keywords
# for

# comments in python
# Importents of comments
""" this is the my
first program
and this is the my first day of the python program """

a=10
b=20
print(a+b)

print(a-b)

# Built in functions in python
num=5
print(num*num)
num1=7
print(num1*num1)
num2=234
print(num2*num2)
def square(n):
  print(n*n)
square(123)
square(24)

# id()
x=100
print(id(x))

my_name="venkatesh j m"
print(my_name)

print(id(my_name))

# bin()
bin(123)

# print(bin(234.23))
# this givs the error because of float numbers are  not converted in binary

bin(10)
# bin(10.2)
# bin("s")

# math functions
# pow() function
print(2**3)
print(2.0,3)
print(pow(2.0,3))

# round() returns the version of specific numbers
num=3.232
print(round(num))

print(round(num,2))
print(round(num,0))
print(round(num,3))

# abs returns the absulute number
print(abs(10))
print(abs(10.2))
print(abs(2+3j))

